### ISSUE TITLE
Broken URL at https://registry.field33.com/

### ISSUE THREAD

**Issue by msm-code** [field33/ontologies#13]
1. I've opened https://registry.field33.com/field/@fld33/relations/0.2.0
2. Github link is https://github.com/field33/ontologies/tree/main/%40fld33/relations
3. The link is broken

I'm not currently an user, just browsing around and decided to let you know.

**Comment by bdart** [comment]
Good catch @msm-code I'll scan for outdated repository links

**Comment by bdart** [comment]
@msm-code the packages are published with the changes made in the Closing PR
